name: Test compilation

on: [push, pull_request]

env:
  OCAML_VERSION: 4.07.1+flambda
  COQ_VERSION: 8.12.2
  METACOQ_VERSION: 1.0~beta2+8.12

jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        target: [ submodules ]

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Try to restore opam cache
      #   id: opam-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: "~/.opam"
      #     key: opam-${{ matrix.target }}-${{github.base_ref}}-${{github.ref}} 
      #     restore-keys: |
      #       opam-${{ matrix.target }}--refs/heads/${{github.base_ref}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-version: ${{ env.OCAML_VERSION }}

      - run: opam repo add coq-released https://coq.inria.fr/opam/released
      - run: opam install coq.${{ env.COQ_VERSION }} coq-metacoq.${{ env.METACOQ_VERSION }}

      - run: opam install .
      - run: opam remove coq-metacoq-parametricity coq-metacoq-nested-induction
