name: Test compilation

on: [push, pull_request]

env:
  OCAML_VERSION: 4.07.1+flambda
  COQ_VERSION: 8.12.0
  METACOQ_VERSION: 7281139

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Try to restore opam cache
      #   id: opam-cache
      #   uses: actions/cache@v2
      #   with:
      #     path: "~/.opam"
      #     key: opam-${{ matrix.target }}-${{github.base_ref}}-${{github.ref}} 
      #     restore-keys: |
      #       opam-${{ matrix.target }}--refs/heads/${{github.base_ref}}

      - name: Install OCaml
        uses: avsm/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml-variants.${{ env.OCAML_VERSION }}
          opam-local-packages: |
            !*.opam

      - name: Install Coq
        run: |
          opam repo add coq-released https://coq.inria.fr/opam/released
          opam install coq.${{ env.COQ_VERSION }}
      - name: Install dev version of MetaCoq (commit ${{ env.METACOQ_VERSION}})
        run: |
          opam pin add -n -y -k git coq-metacoq-template.dev "https://github.com/MetaCoq/metacoq.git#${{ env.METACOQ_VERSION }}"
          opam pin add -n -y -k git coq-metacoq-pcuic.dev "https://github.com/MetaCoq/metacoq.git#${{ env.METACOQ_VERSION }}"
          opam pin add -n -y -k git coq-metacoq-translations.dev "https://github.com/MetaCoq/metacoq.git#${{ env.METACOQ_VERSION }}"
          opam install coq-metacoq-template.dev coq-metacoq-pcuic.dev coq-metacoq-translations.dev

      - name: Compile this project
        run: |
          opam install coq-metacoq-parametricity
          opam install coq-metacoq-nested-induction

      - name: Cleanup
        run: opam remove coq-metacoq-parametricity coq-metacoq-nested-induction
